### ISSUE TITLE
Systemcheck: Layoutanpassung

### ISSUE THREAD

**Issue by franikowsp** [iqb-berlin/testcenter#359]
Im kopierten Systemcheck von hier https://github.com/iqb-berlin/iqb-berlin.github.io/wiki/2.7-System-Check scheint es keine Möglichkeit zu geben, das Layout anzupassen. Es betrifft unserer Sichtung nach allerdings erstmal nur den Default für das MC-Element: 

![image](https://github.com/iqb-berlin/testcenter/assets/60889089/56b04095-947d-481b-9b38-e2c623a633f2)

Das sollte besser untereinander gelistet werden. Sollten Checklists davon auch betroffen sein (noch nicht getestet), wäre ein entsprechende Listung untereinander ebenfalls sinnvoll.

# Beschreibung
* Hatte mal kurz probiert, was anzupassen wäre: Ggf. könnte der `display`-Style für `.mat-radio-button` geändert werden von `inline-block` auf `block`: 
```css
.mat-radio-button {
    display: block;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
    outline: 0;
}
```
